# Spring properties
spring:
  application:
    name: apigateway-service  # Identify this application
    
# Mapping
zuul:
  routes:
    oauth:
      path: /oauth/**
      serviceId: AUTH-SERVICE
      stripPrefix: false

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port