# Spring properties
spring:
  application:
    name: auth-service  # Id de la applicación

# Eureka Discovery Server
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # NO PARA PRODUCCION
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port